# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20170831_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
