# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='content',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
