# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20170918_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JokeUser',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='is_original',
        ),
        migrations.CreateModel(
            name='JokeUser',
            fields=[
                ('joke_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jokes.Joke')),
                ('is_original', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('jokes.joke',),
        ),
    ]
